# Generated by Django 4.0 on 2021-12-20 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='rating',
            new_name='ratings',
        ),
    ]
