# Generated by Django 4.0 on 2021-12-22 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_game_gameimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='gameImage',
        ),
    ]
