# Generated by Django 4.0 on 2021-12-24 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_game_gameimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=300)),
                ('publishDate', models.DateField()),
                ('ofGame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.game')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.user')),
            ],
        ),
    ]
