# Generated by Django 4.0 on 2021-12-27 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_news_award_winner_game_company_game_developer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='ofGame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.game'),
        ),
    ]
