# Generated by Django 4.0 on 2022-01-01 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
