# Generated by Django 4.0 on 2022-01-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proteam',
            name='ofGame',
        ),
        migrations.AddField(
            model_name='proteam',
            name='ofGame',
            field=models.ManyToManyField(to='home.Game'),
        ),
    ]
