# Generated by Django 4.0 on 2022-01-01 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_proteam_ofgame_proteam_ofgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
