# Generated by Django 4.0 on 2022-01-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
