# Generated by Django 4.0 on 2022-01-15 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_player'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
